# ?? ??? ???? ??? ?? ??!
spring:
  batch:
    job:
      names: ${job.name:NONE}

    # ????? ?? ??? ?? (https://hangjastar.tistory.com/231 ??)
    # ??? ???? NEVER, ? ??? ALWAYS or EMBEDDED (default)

